
const CONSTANTS = {
  // singles
  LOADING: 'LOADING',
  DATABASE_LOGIN: 'FIREBASE_LOGIN',
  DATABASE_LOGIN_RESET: 'FIREBASE_LOGIN_RESET',
  UPDATE_SHOP: 'UPDATE_SHOP',
  UPDATE_SHOP_DOMAIN: 'UPDATE_SHOP_DOMAIN',
  UPDATE_CURRENT_PATH: 'UPDATE_CURRENT_PATH',
  INSTALL_SET_DATA: 'INSTALL_SET_DATA',
  INSTALL_SET_DATA_RESET: 'INSTALL_SET_DATA_RESET',
  UPDATE_BILLING: 'UPDATE_BILLING',
}

export default CONSTANTS